CREATE procedure [dbo].[ISP_Seller_Load_After30thJune]
AS
-- DROP TABLE [HR].[Tbl_Seller_Details_Staging]
 Truncate table [HR].[Tbl_Seller_Details_Staging]

INSERT INTO [HR].[Tbl_Seller_Details_Staging]
           ([Alias]
           ,[FullName]
           ,[PositionNumber]
           ,[PersonnelNumber]
           ,[Country]
           ,[FY_ManagerAlias]
           ,[FY_ManagerFullName]
           ,[FY_Org]
           ,[FY_RS]
           ,[FY_Q1]
           ,[FY_Q2]
		    ,[CY_ManagerAlias]
           ,[CY_ManagerFullName]          
           ,[CY_Org]
           ,[CY_RoleSummary]
           ,[CY_Q1]
           ,[CY_Q2]
           ,[ReviewStatus]
           ,[edm_fyenddate]
           ,[edm_fystartdate]
           ,[edm_plansellerid]
           ,[isp_isbubbled]
           ,[isp_istouched]
           ,[ISPReviewReason]
           ,[isp_reviewed]
		   ,[isp_level1]
           ,[isp_level2]
           ,[isp_Level3]
		    ,[Reports_To_Level_1_Email]
      ,[Reports_To_Level_1_Full_Name]
      ,[Reports_To_Level_2_Email]
      ,[Reports_To_Level_2_Full_Name]
      ,[Reports_To_Level_3_Email]
      ,[Reports_To_Level_3_Full_Name]
      ,[Reports_To_Level_4_Email]
      ,[Reports_To_Level_4_Full_Name]
      ,[Reports_To_Level_5_Email]
      ,[Reports_To_Level_5_Full_Name]
      ,[Reports_To_Level_6_Email]
      ,[Reports_To_Level_6_Full_Name]
      ,[Reports_To_Level_7_Email]
      ,[Reports_To_Level_7_Full_Name]
           ,[ISPLastModifiedDate]
           ,[statecode],[FY_IncentivePlan]
      ,[FY_CostCenter]
      ,[CY_CareerStage]
      ,[CY_IncentivePlan]
      ,[CY_CostCenter],[FY_CareerStage])
  SELECT 
 TSD.[Alias]
,TSD.FullName
,TSD.[PositionNumber]
,TSD.PersonnelNumber
,Cn.isp_name AS [Country]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYSeller.[isp_name] else TSD.[CY_ManagerAlias] end AS [FY_ManagerAlias]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYManagername.Full_Name ELSE TSD.[CY_ManagerFullName] end [FY_ManagerFullName] 
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYOrg.[isp_name] else TSD.[CY_Org] end [FY_Org]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYRS.[isp_name] else TSD.[CY_RoleSummary] end [FY_RS]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYQ1.[isp_name] else TSD.[CY_Q1]  end [FY_Q1]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYQ2.[isp_name] else TSD.[CY_Q2] end [FY_Q2]
,TSD.[CY_ManagerAlias]
,TSD.[CY_ManagerFullName]
,TSD.[CY_Org]
,TSD.[CY_RoleSummary]
,TSD.[CY_Q1]
,TSD.[CY_Q2]
,CASE WHEN P.[edm_reviewstatus] = 757580000 THEN 'Pending'
	WHEN P.[edm_reviewstatus] = 757580002 THEN 'Approved'
	WHEN P.[edm_reviewstatus] = 757580003 THEN 'Exception'
	WHEN P.[edm_reviewstatus] = 757580001 THEN 'Reviewed'
END ReviewStatus 
,P.[edm_fyenddate]
,P.[edm_fystartdate] 
,P.[edm_plansellerid] -- UniqueID    
,P.[isp_isbubbled]
,P.[isp_istouched]
,P.[isp_rereviewreason] AS ISPReviewReason
,P.[isp_reviewed]  
,P.[isp_level1]
,P.[isp_level2]
,P.[isp_Level3]
,TSD.[Reports_To_Level_1_Email]
,TSD.[Reports_To_Level_1_Full_Name]
,TSD.[Reports_To_Level_2_Email]
,TSD.[Reports_To_Level_2_Full_Name]
,TSD.[Reports_To_Level_3_Email]
,TSD.[Reports_To_Level_3_Full_Name]
,TSD.[Reports_To_Level_4_Email]
,TSD.[Reports_To_Level_4_Full_Name]
,TSD.[Reports_To_Level_5_Email]
,TSD.[Reports_To_Level_5_Full_Name]
,TSD.[Reports_To_Level_6_Email]
,TSD.[Reports_To_Level_6_Full_Name]
,TSD.[Reports_To_Level_7_Email]
,TSD.[Reports_To_Level_7_Full_Name]
,P.[modifiedon] AS ISPLastModifiedDate
,P.[statecode]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYIP.[isp_name] else TSD.CY_IncentivePlan end [FYIP]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYCC.[isp_name] else TSD.CY_CostCenter end [FYCC]
,TSD.[CY_CareerStage]
,TSD.[CY_IncentivePlan]
,TSD.[CY_CostCenter]
,case WHEN P.[edm_reviewstatus] = 757580002 THEN FYCS.[isp_name] else TSD.CY_CareerStage end [FYCS]
FROM [HR].[Tbl_Seller_Details_30thJune] TSD 
LEFT JOIN [dbo].[Isp_worker] PSeller ON PSeller.isp_name = TSD.Alias AND PSeller.statecode=0
LEFT JOIN  [dbo].[PlanSeller] P ON P.edm_worker = PSeller.[isp_workerid] 
LEFT JOIN [dbo].[Isp_country] Cn On PSeller.[isp_country] = Cn.[isp_countryid]
-- All FY Seller Info
LEFT JOIN [dbo].[Isp_Org] FYOrg On FYOrg.[isp_orgid] = P.[edm_org]
LEFT JOIN [dbo].[Isp_qualifier1] FYQ1 on P.edm_qualifier1 = FYQ1.[isp_qualifier1id]
LEFT JOIN [dbo].[Isp_qualifier2] FYQ2 on P.edm_qualifier2 = FYQ2.[isp_qualifier2id]
LEFT JOIN [dbo].Isp_costcenter FYCC on P.edm_costcenter = FYCC.[Isp_costcenterid]
LEFT JOIN [dbo].Isp_careerstage FYCS on P.isp_fycareerstage = FYCS.[Isp_careerstageid]
LEFT JOIN [dbo].Isp_incentiveplan FYIP on P.[edm_incentiveplan] = FYIP.[Isp_incentiveplanid]
LEFT JOIN [dbo].[Isp_rolesummary] FYRS on P.isp_rolesummary = FYRS.[isp_rolesummaryid]
LEFT JOIN [dbo].[Isp_worker] FYSeller ON FYSeller.isp_workerid =P.isp_fymanager
LEFT JOIN [dbo].[HRDataLake_CYData_Staging] FYManagerName on FYManagerName.Email= FYSeller.[isp_name]