export interface IEDMChangeRequest {
    id: number,
    icAlias:string,
    employeeName: string,
    requestStatus: string,
    proposedFutureYearManager: string,
    currentFutureYearManager: string,
    currentYearManager: string,
    submittedBy: string,
    submittedDate: string,
    approvedRejectedBy: string,
    approvedRejectedDate: string,
    requestorComments: string,
    approverComments: string,
    canApprove:boolean,
}

export interface IEDMChangeTaxonomyCorrection {
    icAlias: string,
    employeeName: string,
    requestStatus: string,
    requestBy: string,
    requestByIcAlias: string,
    requestDate: string,
    reviewer: string,
    cyOrg: string,
    fyOrg: string,
    proposedOrg: string,
    cyRoleSummary: string,
    fyRoleSummary: string,
    proposedRoleSummary: string,
    cyQ1: string,
    fyQ1: string,
    proposedQ1: string,
    cyQ2: string,
    fyQ2: string,
    proposedQ2: string,
    cyCareerStage: string,
    fyCareerStage: string,
    proposedCareerStage: string,
    cyIncentivePlan: string,
    fyIncentivePlan: string,
    proposedIncentivePlan: string,
    cyCostCenter: string,
    fyCostCenter: string,
    proposedCostCenter: string,
  }

   