CREATE TABLE [HR].[Scripts_Template] (
    [ID]                        INT             IDENTITY (1, 1) NOT NULL,
    [Section]                   NVARCHAR (50)   NULL,
    [Seq]                       INT             NOT NULL,
    [CY_Org]                    NVARCHAR (MAX)  NULL,
    [CY_Profession]             NVARCHAR (500)  NULL,
    [CY_Descipline]             NVARCHAR (500)  NULL,
    [CY_RoleSummary]            NVARCHAR (50)   NULL,
    [CY_ABT]                    NVARCHAR (50)   NULL,
    [CY_Q1]                     NVARCHAR (50)   NULL,
    [CY_Q2]                     NVARCHAR (50)   NULL,
    [CY_IncentivePlan]          NVARCHAR (500)  NULL,
    [CY_CareerStage]            NVARCHAR (500)  NULL,
    [FY_Org]                    NVARCHAR (MAX)  NULL,
    [FY_Profession]             NVARCHAR (500)  NULL,
    [FY_Descipline]             NVARCHAR (500)  NULL,
    [FY_RoleSummary]            NVARCHAR (50)   NULL,
    [FY_ABT]                    NVARCHAR (50)   NULL,
    [FY_Q1]                     NVARCHAR (50)   NULL,
    [FY_Q2]                     NVARCHAR (50)   NULL,
    [FY_IncentivePlan]          NVARCHAR (500)  NULL,
    [FY_CareerStage]            NVARCHAR (500)  NULL,
    [Priority]                  INT             NULL,
    [ContextDescription]        NVARCHAR (MAX)  NULL,
    [IsActive]                  BIT             NOT NULL,
    [CreatedBy]                 NVARCHAR (255)  NOT NULL,
    [CreatedOn]                 DATETIME2 (7)   NOT NULL,
    [ModifiedBy]                NVARCHAR (255)  NOT NULL,
    [ModifiedOn]                DATETIME2 (7)   NOT NULL,
    [ScenarioName]              NVARCHAR (1000) NULL,
    [Exclusion]                 NVARCHAR (1000) NULL,
    [DisciplineContextOptional] NVARCHAR (1000) NULL,
    [Title]                     NVARCHAR (1000) NULL,
    [IsFinal]                   BIT             DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

