CREATE TABLE [HR].[Tbl_Seller_Details_30thJune] (
    [Alias]                        NVARCHAR (50)    NULL,
    [FullName]                     NVARCHAR (MAX)   NULL,
    [PositionNumber]               INT              NULL,
    [PersonnelNumber]              INT              NULL,
    [Country]                      NVARCHAR (MAX)   NULL,
    [FY_ManagerAlias]              NVARCHAR (MAX)   NULL,
    [FY_ManagerFullName]           NVARCHAR (MAX)   NULL,
    [FY_Org]                       NVARCHAR (MAX)   NULL,
    [FY_RS]                        NVARCHAR (MAX)   NULL,
    [FY_Q1]                        NVARCHAR (MAX)   NULL,
    [FY_Q2]                        NVARCHAR (MAX)   NULL,
    [CY_ManagerAlias]              NVARCHAR (50)    NULL,
    [CY_ManagerFullName]           NVARCHAR (MAX)   NULL,
    [CY_Org]                       NVARCHAR (MAX)   NULL,
    [CY_RoleSummary]               NVARCHAR (50)    NULL,
    [CY_Q1]                        NVARCHAR (50)    NULL,
    [CY_Q2]                        NVARCHAR (50)    NULL,
    [ReviewStatus]                 VARCHAR (9)      NULL,
    [edm_fyenddate]                DATETIME2 (7)    NULL,
    [edm_fystartdate]              DATETIME2 (7)    NULL,
    [edm_plansellerid]             UNIQUEIDENTIFIER NULL,
    [isp_isbubbled]                BIT              NULL,
    [isp_istouched]                BIT              NULL,
    [ISPReviewReason]              INT              NULL,
    [isp_reviewed]                 BIT              NULL,
    [isp_level1]                   UNIQUEIDENTIFIER NULL,
    [isp_level2]                   UNIQUEIDENTIFIER NULL,
    [isp_Level3]                   UNIQUEIDENTIFIER NULL,
    [Reports_To_Level_1_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_1_Full_Name] NVARCHAR (MAX)   NULL,
    [Reports_To_Level_2_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_2_Full_Name] NVARCHAR (MAX)   NULL,
    [Reports_To_Level_3_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_3_Full_Name] NVARCHAR (MAX)   NULL,
    [Reports_To_Level_4_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_4_Full_Name] NVARCHAR (MAX)   NULL,
    [Reports_To_Level_5_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_5_Full_Name] NVARCHAR (MAX)   NULL,
    [Reports_To_Level_6_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_6_Full_Name] NVARCHAR (MAX)   NULL,
    [Reports_To_Level_7_Email]     NVARCHAR (50)    NULL,
    [Reports_To_Level_7_Full_Name] NVARCHAR (MAX)   NULL,
    [ISPLastModifiedDate]          DATETIME2 (7)    NULL,
    [statecode]                    INT              NULL,
    [FY_IncentivePlan]             NVARCHAR (500)   NULL,
    [FY_CostCenter]                NVARCHAR (500)   NULL,
    [CY_CareerStage]               NVARCHAR (500)   NULL,
    [CY_IncentivePlan]             NVARCHAR (500)   NULL,
    [CY_CostCenter]                NVARCHAR (500)   NULL,
    [FY_CareerStage]               NVARCHAR (500)   NULL
);

