CREATE TABLE HR.Tbl_HRData_FYManagerCorrection (
    id INT IDENTITY(1,1) PRIMARY KEY,
    icAlias NVARCHAR(40),
    cyManagerAlias NVARCHAR(40),
    fyManagerAlias NVARCHAR(40),
    fyCorrectManagerAlias NVARCHAR(40),
    status NVARCHAR(40),
    comment NVARCHAR(500),
    ispUpdateStatus NVARCHAR(40),
    ispErrorDetails NVARCHAR(1000),
    approvedRejectedBy NVARCHAR(40), 
    approvedRejectedDate DATETIME, 
    approverComments NVARCHAR(500),
    isLevel1ApprovalEmailSent bit NOT NULL DEFAULT 0,
    isLevel2ApprovalEmailSent bit NOT NULL DEFAULT 0,
    TwoLevelApprovalRequired bit NOT NULL DEFAULT 0,
	[approvedRejectedByLevel2] [nvarchar](40) NULL,
	[approvedRejectedDateByLevel2] DATETIME NULL,
	[approverRejecterCommentsByLevel2] [nvarchar](100) NULL,
    [flowId] [nvarchar](100) NULL,
    [flowRunId] [nvarchar](100) NULL,
    [flowApprovalId] [nvarchar](100) NULL,
    isActive BIT DEFAULT 1,
    createdBy NVARCHAR(40) not null,
    createdDate DATETIME DEFAULT GETUTCDATE(),
    modifiedBy NVARCHAR(40) not null,
    modifiedDate DATETIME DEFAULT GETUTCDATE(),
    rowVer rowversion
);