CREATE TABLE [HR].[Tbl_HRData_ToolInput] (
    [IC]                        NVARCHAR (255)  NOT NULL,
    [R1_ConversationStatus]     NVARCHAR (255)  NULL,
    [R1_EDMValidation]          NVARCHAR (255)  NULL,
    [R1_Comments]               NVARCHAR (1255) NULL,
    [R1_Org]                    NVARCHAR (255)  NULL,
    [R1_RS]                     NVARCHAR (255)  NULL,
    [R1_Q1]                     NVARCHAR (255)  NULL,
    [R1_Q2]                     NVARCHAR (255)  NULL,
    [R1_updatedby]              NVARCHAR (255)  NULL,
    [R1_update]                 DATETIME        NULL,
    [R1_CoversationLevel]       NVARCHAR (255)  NULL,
    [R2_ConversationStatus]     NVARCHAR (255)  NULL,
    [R2_EDMValidation]          NVARCHAR (255)  NULL,
    [R2_Comments]               NVARCHAR (1255) NULL,
    [R2_Org]                    NVARCHAR (255)  NULL,
    [R2_RS]                     NVARCHAR (255)  NULL,
    [R2_Q1]                     NVARCHAR (255)  NULL,
    [R2_Q2]                     NVARCHAR (255)  NULL,
    [R2_CoversationLevel]       NVARCHAR (255)  NULL,
    [R2_updatedby]              NVARCHAR (255)  NULL,
    [R2_update]                 DATETIME        NULL,
    [R1_FY23CorrectManager]     NVARCHAR (255)  NULL,
    [R2_FY23CorrectManager]     NVARCHAR (255)  NULL,
    [Status]                    NCHAR (25)      NULL,
    [DecisionMakerAlias]        NVARCHAR (25)   NULL,
    [DecisionMadeOn]            DATETIME        NULL,
    [DecisionMakerComments]     NVARCHAR (MAX)  NULL,
    [FYManagerChangeApprovedOn] DATETIME        NULL,
    [IsEDMOverride]             NVARCHAR (10)   NULL,
    [Area]                      NVARCHAR (50)   NULL,
    [DecisionMakerName]         NVARCHAR (100)  NULL,
    [RequestID]                 INT             IDENTITY (1, 1) NOT NULL,
    [SendingEmailsent]          NVARCHAR (10)   NULL,
    [FY_IncentivePlan]          NVARCHAR (50)   NULL,
    [FY_CostCenter]             NVARCHAR (250)  NULL,
    [ISPUpdateStatus]           NVARCHAR (500)  NULL,
    [ISPErrorDetails]           NVARCHAR (500)  NULL,
    [SendStayScriptFollowed]    BIT             NULL,
    [ReceiveScriptFollowed]     BIT             NULL,
    CONSTRAINT [Tbl_HRDa__3214EC26B04A44C4_PK] PRIMARY KEY CLUSTERED ([IC] ASC)
);

