CREATE TABLE [HR].[Tbl_HRData_Staging] (
    [IC]                           NVARCHAR (50)  NULL,
    [IC_FullName]                  NVARCHAR (MAX) NULL,
    [Location]                     NVARCHAR (MAX) NULL,
    [RoleChange]                   NVARCHAR (MAX) NULL,
    [CY_ManagerAlias]              NVARCHAR (50)  NULL,
    [CY_ManagerFullName]           NVARCHAR (MAX) NULL,
    [CY_Org]                       NVARCHAR (MAX) NULL,
    [CY_RoleSummary]               NVARCHAR (50)  NULL,
    [CY_Q1]                        NVARCHAR (50)  NULL,
    [CY_Q2]                        NVARCHAR (50)  NULL,
    [FY_ManagerAlias]              NVARCHAR (MAX) NULL,
    [FY_ManagerFullName]           NVARCHAR (MAX) NULL,
    [FY_Org]                       NVARCHAR (MAX) NULL,
    [FY_RoleSummary]               NVARCHAR (MAX) NULL,
    [FY_Q1]                        NVARCHAR (MAX) NULL,
    [FY_Q2]                        NVARCHAR (MAX) NULL,
    [FYManagerChange]              VARCHAR (1)    NOT NULL,
    [RecordModifiedDate]           DATETIME2 (7)  NULL,
    [Script]                       NVARCHAR (MAX) NULL,
    [Reports_To_Level_1_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_1_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_2_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_2_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_3_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_3_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_4_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_4_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_5_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_5_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_6_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_6_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_7_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_7_Full_Name] NVARCHAR (MAX) NULL,
    [ID]                           INT            IDENTITY (1, 1) NOT NULL,
    [FY_IncentivePlan]             NVARCHAR (500) NULL,
    [FY_CostCenter]                NVARCHAR (500) NULL,
    [CY_CareerStage]               NVARCHAR (500) NULL,
    [CY_IncentivePlan]             NVARCHAR (500) NULL,
    [CY_CostCenter]                NVARCHAR (500) NULL,
    [FY_CareerStage]               NVARCHAR (500) NULL,
    [CY_Profession]                nvarchar (500) NULL,
    [CY_Discipline]                nvarchar (500) NULL,
    [FY_Profession]                nvarchar (500) NULL,
    [FY_Discipline]                nvarchar (500) NULL,
    [IsConversationRequired]       BIT NULL
);

