CREATE TABLE [dbo].[HRDataLake_CYData_staging_V2] (
    [Personnel_Number]             INT            NULL,
    [Email]                        NVARCHAR (50)  NULL,
    [Full_Name]                    NVARCHAR (MAX) NULL,
    [ManagerEmail]                 NVARCHAR (50)  NULL,
    [Reports_To_Full_Name]         NVARCHAR (MAX) NULL,
    [Skip_Level_Email]             NVARCHAR (50)  NULL,
    [Org]                          NVARCHAR (50)  NULL,
    [Position_Number]              INT            NULL,
    [Qualifier_1]                  NVARCHAR (50)  NULL,
    [Qualifier_2]                  NVARCHAR (50)  NULL,
    [Role_Summary]                 NVARCHAR (50)  NULL,
    [Reports_To_Level_1_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_2_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_3_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_4_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_5_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_6_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_7_Email]     NVARCHAR (50)  NULL,
    [Reports_To_Level_1_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_2_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_3_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_4_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_5_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_6_Full_Name] NVARCHAR (MAX) NULL,
    [Reports_To_Level_7_Full_Name] NVARCHAR (MAX) NULL,
    [CostCenter]                   NVARCHAR (MAX) NULL,
    [IncentivePlan]                NVARCHAR (50)  NULL,
    [CareerStage]                  NVARCHAR (50)  NULL
);

