CREATE TABLE [dbo].[Isp_worker] (
    [createdby]                  UNIQUEIDENTIFIER NULL,
    [createdbyname]              NVARCHAR (MAX)   NULL,
    [createdbyyominame]          NVARCHAR (MAX)   NULL,
    [createdon]                  DATETIME2 (7)    NULL,
    [createdonbehalfby]          UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]      NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]  NVARCHAR (MAX)   NULL,
    [importsequencenumber]       INT              NULL,
    [isp_alias]                  NVARCHAR (MAX)   NULL,
    [isp_careerstage]            NVARCHAR (MAX)   NULL,
    [isp_careerstagecode]        NVARCHAR (MAX)   NULL,
    [isp_country]                UNIQUEIDENTIFIER NULL,
    [isp_countryname]            NVARCHAR (MAX)   NULL,
    [isp_firstname]              NVARCHAR (MAX)   NULL,
    [isp_isedmeligible]          BIT              NULL,
    [isp_lastname]               NVARCHAR (MAX)   NULL,
    [isp_level]                  NVARCHAR (MAX)   NULL,
    [isp_manager]                UNIQUEIDENTIFIER NULL,
    [isp_managerindicatorid]     INT              NULL,
    [isp_managername]            NVARCHAR (MAX)   NULL,
    [isp_middlename]             NVARCHAR (MAX)   NULL,
    [isp_monthsatms]             INT              NULL,
    [isp_name]                   NVARCHAR (MAX)   NULL,
    [isp_openpositionindicator]  BIT              NULL,
    [isp_payscaleareacode]       NVARCHAR (MAX)   NULL,
    [isp_payscaleareaname]       NVARCHAR (MAX)   NULL,
    [isp_personnelnumber]        INT              NULL,
    [isp_positionnumber]         INT              NULL,
    [isp_terminationdate]        DATETIME2 (7)    NULL,
    [isp_workercode]             NVARCHAR (MAX)   NULL,
    [isp_workerid]               UNIQUEIDENTIFIER NULL,
    [isp_workerstatus]           INT              NULL,
    [modifiedby]                 UNIQUEIDENTIFIER NULL,
    [modifiedbyname]             NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]         NVARCHAR (MAX)   NULL,
    [modifiedon]                 DATETIME2 (7)    NULL,
    [modifiedonbehalfby]         UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]     NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame] NVARCHAR (MAX)   NULL,
    [overriddencreatedon]        DATETIME2 (7)    NULL,
    [ownerid]                    UNIQUEIDENTIFIER NULL,
    [owneridname]                NVARCHAR (MAX)   NULL,
    [owneridtype]                NVARCHAR (MAX)   NULL,
    [owneridyominame]            NVARCHAR (MAX)   NULL,
    [owningbusinessunit]         UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]     NVARCHAR (MAX)   NULL,
    [owningteam]                 UNIQUEIDENTIFIER NULL,
    [owninguser]                 UNIQUEIDENTIFIER NULL,
    [statecode]                  INT              NULL,
    [statuscode]                 INT              NULL,
    [timezoneruleversionnumber]  INT              NULL,
    [utcconversiontimezonecode]  INT              NULL,
    [versionnumber]              BIGINT           NULL
);

