CREATE TABLE [dbo].[Isp_costcenter_staging] (
    [createdby]                  UNIQUEIDENTIFIER NULL,
    [createdbyname]              NVARCHAR (MAX)   NULL,
    [createdbyyominame]          NVARCHAR (MAX)   NULL,
    [createdon]                  DATETIME2 (7)    NULL,
    [createdonbehalfby]          UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]      NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]  NVARCHAR (MAX)   NULL,
    [importsequencenumber]       INT              NULL,
    [isp_companycode]            UNIQUEIDENTIFIER NULL,
    [isp_companycodename]        NVARCHAR (MAX)   NULL,
    [isp_costcenterbegindate]    DATETIME2 (7)    NULL,
    [isp_costcenterenddate]      DATETIME2 (7)    NULL,
    [isp_costcenterid]           UNIQUEIDENTIFIER NULL,
    [isp_costcentername]         NVARCHAR (MAX)   NULL,
    [isp_country]                UNIQUEIDENTIFIER NULL,
    [isp_countryname]            NVARCHAR (MAX)   NULL,
    [isp_enddate]                DATETIME2 (7)    NULL,
    [isp_fiscalyear]             INT              NULL,
    [isp_glcompanycode]          INT              NULL,
    [isp_name]                   NVARCHAR (MAX)   NULL,
    [isp_org]                    UNIQUEIDENTIFIER NULL,
    [isp_orgname]                NVARCHAR (MAX)   NULL,
    [isp_profitcenter]           UNIQUEIDENTIFIER NULL,
    [isp_profitcentername]       NVARCHAR (MAX)   NULL,
    [isp_salesdistrict]          UNIQUEIDENTIFIER NULL,
    [isp_salesdistrictname]      NVARCHAR (MAX)   NULL,
    [isp_saleslocation]          UNIQUEIDENTIFIER NULL,
    [isp_saleslocationname]      NVARCHAR (MAX)   NULL,
    [isp_startdate]              DATETIME2 (7)    NULL,
    [modifiedby]                 UNIQUEIDENTIFIER NULL,
    [modifiedbyname]             NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]         NVARCHAR (MAX)   NULL,
    [modifiedon]                 DATETIME2 (7)    NULL,
    [modifiedonbehalfby]         UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]     NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame] NVARCHAR (MAX)   NULL,
    [organizationid]             UNIQUEIDENTIFIER NULL,
    [organizationidname]         NVARCHAR (MAX)   NULL,
    [overriddencreatedon]        DATETIME2 (7)    NULL,
    [statecode]                  INT              NULL,
    [statuscode]                 INT              NULL,
    [timezoneruleversionnumber]  INT              NULL,
    [utcconversiontimezonecode]  INT              NULL,
    [versionnumber]              BIGINT           NULL
);

