CREATE TABLE [dbo].[Isp_jobrole] (
    [createdby]                  UNIQUEIDENTIFIER NULL,
    [createdbyname]              NVARCHAR (MAX)   NULL,
    [createdbyyominame]          NVARCHAR (MAX)   NULL,
    [createdon]                  DATETIME2 (7)    NULL,
    [createdonbehalfby]          UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]      NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]  NVARCHAR (MAX)   NULL,
    [importsequencenumber]       INT              NULL,
    [isp_careerstagecode]        NVARCHAR (MAX)   NULL,
    [isp_disciplinecode]         NVARCHAR (MAX)   NULL,
    [isp_gotomarketposition]     UNIQUEIDENTIFIER NULL,
    [isp_gotomarketpositionname] NVARCHAR (MAX)   NULL,
    [isp_jobrolecode]            NVARCHAR (MAX)   NULL,
    [isp_jobroleid]              UNIQUEIDENTIFIER NULL,
    [isp_jobrolenumber]          NVARCHAR (MAX)   NULL,
    [isp_name]                   NVARCHAR (MAX)   NULL,
    [isp_professioncode]         NVARCHAR (MAX)   NULL,
    [isp_rolesummary]            UNIQUEIDENTIFIER NULL,
    [isp_rolesummaryname]        NVARCHAR (MAX)   NULL,
    [modifiedby]                 UNIQUEIDENTIFIER NULL,
    [modifiedbyname]             NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]         NVARCHAR (MAX)   NULL,
    [modifiedon]                 DATETIME2 (7)    NULL,
    [modifiedonbehalfby]         UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]     NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame] NVARCHAR (MAX)   NULL,
    [organizationid]             UNIQUEIDENTIFIER NULL,
    [organizationidname]         NVARCHAR (MAX)   NULL,
    [overriddencreatedon]        DATETIME2 (7)    NULL,
    [statecode]                  INT              NULL,
    [statuscode]                 INT              NULL,
    [timezoneruleversionnumber]  INT              NULL,
    [utcconversiontimezonecode]  INT              NULL,
    [versionnumber]              BIGINT           NULL
);

