CREATE TABLE [dbo].[Isp_seller_staging] (
    [createdby]                  UNIQUEIDENTIFIER NULL,
    [createdbyname]              NVARCHAR (MAX)   NULL,
    [createdbyyominame]          NVARCHAR (MAX)   NULL,
    [createdon]                  DATETIME2 (7)    NULL,
    [createdonbehalfby]          UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]      NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]  NVARCHAR (MAX)   NULL,
    [importsequencenumber]       INT              NULL,
    [isp_alias]                  NVARCHAR (MAX)   NULL,
    [isp_area]                   UNIQUEIDENTIFIER NULL,
    [isp_areaname]               NVARCHAR (MAX)   NULL,
    [isp_careerstage]            UNIQUEIDENTIFIER NULL,
    [isp_careerstagename]        NVARCHAR (MAX)   NULL,
    [isp_costcenter]             UNIQUEIDENTIFIER NULL,
    [isp_costcentername]         NVARCHAR (MAX)   NULL,
    [isp_country]                UNIQUEIDENTIFIER NULL,
    [isp_countryname]            NVARCHAR (MAX)   NULL,
    [isp_currentlyactive]        BIT              NULL,
    [isp_gotomarketposition]     UNIQUEIDENTIFIER NULL,
    [isp_gotomarketpositionname] NVARCHAR (MAX)   NULL,
    [isp_incentiveplan]          UNIQUEIDENTIFIER NULL,
    [isp_incentiveplanname]      NVARCHAR (MAX)   NULL,
    [isp_isfy]                   BIT              NULL,
    [isp_job]                    UNIQUEIDENTIFIER NULL,
    [isp_jobname]                NVARCHAR (MAX)   NULL,
    [isp_jobrole]                UNIQUEIDENTIFIER NULL,
    [isp_jobrolename]            NVARCHAR (MAX)   NULL,
    [isp_level]                  INT              NULL,
    [isp_manager]                UNIQUEIDENTIFIER NULL,
    [isp_managerindicator]       INT              NULL,
    [isp_managername]            NVARCHAR (MAX)   NULL,
    [isp_name]                   NVARCHAR (MAX)   NULL,
    [isp_org]                    UNIQUEIDENTIFIER NULL,
    [isp_orgname]                NVARCHAR (MAX)   NULL,
    [isp_personnelnumber]        INT              NULL,
    [isp_positionentrydate]      DATETIME2 (7)    NULL,
    [isp_positionfromdate]       DATETIME2 (7)    NULL,
    [isp_positionnumber]         INT              NULL,
    [isp_positiontodate]         DATETIME2 (7)    NULL,
    [isp_projectdescription]     NVARCHAR (MAX)   NULL,
    [isp_qualifier1]             UNIQUEIDENTIFIER NULL,
    [isp_qualifier1name]         NVARCHAR (MAX)   NULL,
    [isp_qualifier2]             UNIQUEIDENTIFIER NULL,
    [isp_qualifier2name]         NVARCHAR (MAX)   NULL,
    [isp_roleenddate]            DATETIME2 (7)    NULL,
    [isp_rolestartdate]          DATETIME2 (7)    NULL,
    [isp_rolesummary]            UNIQUEIDENTIFIER NULL,
    [isp_rolesummaryname]        NVARCHAR (MAX)   NULL,
    [isp_salesdistrict]          UNIQUEIDENTIFIER NULL,
    [isp_salesdistrictname]      NVARCHAR (MAX)   NULL,
    [isp_saleslocation]          UNIQUEIDENTIFIER NULL,
    [isp_saleslocationname]      NVARCHAR (MAX)   NULL,
    [isp_sellerid]               UNIQUEIDENTIFIER NULL,
    [isp_sellermonthend]         BIT              NULL,
    [isp_standardtitle]          UNIQUEIDENTIFIER NULL,
    [isp_standardtitlename]      NVARCHAR (MAX)   NULL,
    [isp_subregion]              UNIQUEIDENTIFIER NULL,
    [isp_subregionname]          NVARCHAR (MAX)   NULL,
    [isp_worker]                 UNIQUEIDENTIFIER NULL,
    [isp_workername]             NVARCHAR (MAX)   NULL,
    [modifiedby]                 UNIQUEIDENTIFIER NULL,
    [modifiedbyname]             NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]         NVARCHAR (MAX)   NULL,
    [modifiedon]                 DATETIME2 (7)    NULL,
    [modifiedonbehalfby]         UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]     NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame] NVARCHAR (MAX)   NULL,
    [organizationid]             UNIQUEIDENTIFIER NULL,
    [organizationidname]         NVARCHAR (MAX)   NULL,
    [overriddencreatedon]        DATETIME2 (7)    NULL,
    [statecode]                  INT              NULL,
    [statuscode]                 INT              NULL,
    [timezoneruleversionnumber]  INT              NULL,
    [utcconversiontimezonecode]  INT              NULL,
    [versionnumber]              BIGINT           NULL,
    [isp_companycode]            UNIQUEIDENTIFIER NULL,
    [isp_companycodename]        NVARCHAR (MAX)   NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_isp_seller]
    ON [dbo].[Isp_seller_staging]([isp_isfy] ASC)
    INCLUDE([isp_name], [isp_worker]);

