CREATE TABLE [dbo].[MSPeople6_29] (
    [Personnel_Number]             INT            NULL,
    [Email]                        NVARCHAR (50)  NULL,
    [Role_Summary]                 NVARCHAR (50)  NULL,
    [Qualifier_1]                  NVARCHAR (50)  NULL,
    [Qualifier_2]                  NVARCHAR (50)  NULL,
    [Org]                          NVARCHAR (50)  NULL,
    [Reports_To_Email]             NVARCHAR (50)  NULL,
    [Reports_To_Full_Name_Level_7] NVARCHAR (MAX) NULL,
    [Reports_To_Email_Level_2]     NVARCHAR (50)  NULL,
    [Reports_To_Email_Level_4]     NVARCHAR (50)  NULL,
    [Reports_To_Email_Level_1]     NVARCHAR (50)  NULL,
    [Reports_To_Email_Level_5]     NVARCHAR (50)  NULL,
    [Reports_To_Email_Level_6]     NVARCHAR (50)  NULL,
    [Reports_To_Full_Name_Level_3] NVARCHAR (MAX) NULL,
    [Reports_To_Full_Name_Level_6] NVARCHAR (MAX) NULL,
    [Reports_To_Email_Level_3]     NVARCHAR (50)  NULL,
    [Reports_To_Full_Name_Level_4] NVARCHAR (MAX) NULL,
    [Reports_To_Email_Level_7]     NVARCHAR (50)  NULL,
    [Reports_To_Full_Name_Level_1] NVARCHAR (MAX) NULL,
    [Reports_To_Full_Name_Level_2] NVARCHAR (MAX) NULL,
    [Reports_To_Full_Name_Level_5] NVARCHAR (MAX) NULL,
    [Full_Name]                    NVARCHAR (50)  NULL,
    [Reports_To_Full_Name]         NVARCHAR (MAX) NULL
);

