CREATE TABLE [dbo].[PlanSeller] (
    [createdby]                  UNIQUEIDENTIFIER NULL,
    [createdbyname]              NVARCHAR (MAX)   NULL,
    [createdbyyominame]          NVARCHAR (MAX)   NULL,
    [createdon]                  DATETIME2 (7)    NULL,
    [createdonbehalfby]          UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]      NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]  NVARCHAR (MAX)   NULL,
    [edm_comments]               NVARCHAR (MAX)   NULL,
    [edm_costcenter]             UNIQUEIDENTIFIER NULL,
    [edm_costcentername]         NVARCHAR (MAX)   NULL,
    [edm_country]                UNIQUEIDENTIFIER NULL,
    [edm_countryname]            NVARCHAR (MAX)   NULL,
    [edm_fyenddate]              DATETIME2 (7)    NULL,
    [edm_fystartdate]            DATETIME2 (7)    NULL,
    [edm_incentiveplan]          UNIQUEIDENTIFIER NULL,
    [edm_incentiveplanname]      NVARCHAR (MAX)   NULL,
    [edm_job]                    UNIQUEIDENTIFIER NULL,
    [edm_jobname]                NVARCHAR (MAX)   NULL,
    [edm_name]                   NVARCHAR (MAX)   NULL,
    [edm_org]                    UNIQUEIDENTIFIER NULL,
    [edm_orgname]                NVARCHAR (MAX)   NULL,
    [edm_personnel]              INT              NULL,
    [edm_plansellerid]           UNIQUEIDENTIFIER NULL,
    [edm_qualifier1]             UNIQUEIDENTIFIER NULL,
    [edm_qualifier1name]         NVARCHAR (MAX)   NULL,
    [edm_qualifier2]             UNIQUEIDENTIFIER NULL,
    [edm_qualifier2name]         NVARCHAR (MAX)   NULL,
    [edm_reviewstatus]           INT              NULL,
    [edm_sellercy]               UNIQUEIDENTIFIER NULL,
    [edm_sellercyname]           NVARCHAR (MAX)   NULL,
    [edm_sellerfy]               UNIQUEIDENTIFIER NULL,
    [edm_sellerfyname]           NVARCHAR (MAX)   NULL,
    [edm_worker]                 UNIQUEIDENTIFIER NULL,
    [edm_workername]             NVARCHAR (MAX)   NULL,
    [edm_year]                   INT              NULL,
    [importsequencenumber]       INT              NULL,
    [isp_area]                   UNIQUEIDENTIFIER NULL,
    [isp_areaname]               NVARCHAR (MAX)   NULL,
    [isp_compgroup]              UNIQUEIDENTIFIER NULL,
    [isp_compgroupname]          NVARCHAR (MAX)   NULL,
    [isp_cymanager]              UNIQUEIDENTIFIER NULL,
    [isp_cymanagername]          NVARCHAR (MAX)   NULL,
    [isp_fycareerstage]          UNIQUEIDENTIFIER NULL,
    [isp_fycareerstagename]      NVARCHAR (MAX)   NULL,
    [isp_fymanager]              UNIQUEIDENTIFIER NULL,
    [isp_fymanagername]          NVARCHAR (MAX)   NULL,
    [isp_gotomarketposition]     UNIQUEIDENTIFIER NULL,
    [isp_gotomarketpositionname] NVARCHAR (MAX)   NULL,
    [isp_isbubbled]              BIT              NULL,
    [isp_istouched]              BIT              NULL,
    [isp_jobrole]                UNIQUEIDENTIFIER NULL,
    [isp_jobrolename]            NVARCHAR (MAX)   NULL,
    [isp_jobvalidity]            INT              NULL,
    [isp_level0]                 UNIQUEIDENTIFIER NULL,
    [isp_level0name]             NVARCHAR (MAX)   NULL,
    [isp_level1]                 UNIQUEIDENTIFIER NULL,
    [isp_level1name]             NVARCHAR (MAX)   NULL,
    [isp_level2]                 UNIQUEIDENTIFIER NULL,
    [isp_level2name]             NVARCHAR (MAX)   NULL,
    [isp_level3]                 UNIQUEIDENTIFIER NULL,
    [isp_level3name]             NVARCHAR (MAX)   NULL,
    [isp_level4]                 UNIQUEIDENTIFIER NULL,
    [isp_level4name]             NVARCHAR (MAX)   NULL,
    [isp_level5]                 UNIQUEIDENTIFIER NULL,
    [isp_level5name]             NVARCHAR (MAX)   NULL,
    [isp_level6]                 UNIQUEIDENTIFIER NULL,
    [isp_level6name]             NVARCHAR (MAX)   NULL,
    [isp_level7]                 UNIQUEIDENTIFIER NULL,
    [isp_level7name]             NVARCHAR (MAX)   NULL,
    [isp_positionnumber]         INT              NULL,
    [isp_rereviewreason]         INT              NULL,
    [isp_reviewed]               BIT              NULL,
    [isp_role]                   NVARCHAR (MAX)   NULL,
    [isp_rolesummary]            UNIQUEIDENTIFIER NULL,
    [isp_rolesummaryname]        NVARCHAR (MAX)   NULL,
    [isp_saleslocation]          UNIQUEIDENTIFIER NULL,
    [isp_saleslocationname]      NVARCHAR (MAX)   NULL,
    [modifiedby]                 UNIQUEIDENTIFIER NULL,
    [modifiedbyname]             NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]         NVARCHAR (MAX)   NULL,
    [modifiedon]                 DATETIME2 (7)    NULL,
    [modifiedonbehalfby]         UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]     NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame] NVARCHAR (MAX)   NULL,
    [overriddencreatedon]        DATETIME2 (7)    NULL,
    [ownerid]                    UNIQUEIDENTIFIER NULL,
    [owneridname]                NVARCHAR (MAX)   NULL,
    [owneridtype]                NVARCHAR (MAX)   NULL,
    [owneridyominame]            NVARCHAR (MAX)   NULL,
    [owningbusinessunit]         UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]     NVARCHAR (MAX)   NULL,
    [owningteam]                 UNIQUEIDENTIFIER NULL,
    [owninguser]                 UNIQUEIDENTIFIER NULL,
    [statecode]                  INT              NULL,
    [statuscode]                 INT              NULL,
    [timezoneruleversionnumber]  INT              NULL,
    [utcconversiontimezonecode]  INT              NULL,
    [versionnumber]              BIGINT           NULL,
    [isp_companycode]            UNIQUEIDENTIFIER NULL,
    [isp_companycodename]        NVARCHAR (MAX)   NULL
);

