--CREATE CERTIFICATE MySelfSignedCert
--ENCRYPTION BY PASSWORD = '_+12mcaps__+help453)(*&^$2(*^_='
--WITH SUBJECT = 'MCAPS UAT';

--GO
--CREATE SYMMETRIC KEY MySymmetricKey
--WITH ALGORITHM = AES_256 
--ENCRYPTION BY CERTIFICATE MySelfSignedCert;
--GO

IF NOT EXISTS (SELECT * FROM sys.certificates WHERE name = 'MySelfSignedCert')
BEGIN
    CREATE CERTIFICATE MySelfSignedCert
    ENCRYPTION BY PASSWORD = '_+12mcaps__+help453)(*&^$2(*^_='
    WITH SUBJECT = 'MCAPS PROD';
END
GO

IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE name = 'MySymmetricKey')
BEGIN
    CREATE SYMMETRIC KEY MySymmetricKey
    WITH ALGORITHM = AES_256 
    ENCRYPTION BY CERTIFICATE MySelfSignedCert;
END
GO



GRANT REFERENCES ON SYMMETRIC KEY::[MySymmetricKey] TO [MCAPSHELPAPI];
GO
GRANT VIEW DEFINITION ON SYMMETRIC KEY::[MySymmetricKey] TO [MCAPSHELPAPI];
GO
GRANT CONTROL ON SYMMETRIC KEY::[MySymmetricKey] TO [MCAPSHELPAPI];
GO

GRANT VIEW DEFINITION ON Certificate::[MySelfSignedCert] TO [MCAPSHELPAPI];
GO
GRANT CONTROL ON Certificate::[MySelfSignedCert] TO [MCAPSHELPAPI];

GO
--SELECT * FROM sys.database_principals