trigger: none
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  runSettings: '\src\api\MCT.Business.Test\codecoverage.runsettings'
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 'mct1espool'
      image: mct1esptwindows
      os: windows
    stages:
    - stage: stage
      displayName: Gated
      jobs:
      - job: job
        displayName: Job
        steps:
        - task: UseDotNet@2
          displayName: Use .Net 6.0.x
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
            
        - task: DotNetCoreCLI@2
          displayName: MCT.API - restore
          inputs:
            command: 'restore'
            projects: |
              **/*MCT.Api.csproj
              **/*Test.csproj
            feedsToUse: 'select'
            vstsFeed: 'c1eb1d13-5333-4112-95b2-2e514c22c241/e7a9b03a-3e9e-4ae7-b444-a06a80ff3074'
            includeNuGetOrg: false
            continueOnError: true

        - task: DotNetCoreCLI@2
          displayName: MCT.API - build
          inputs:
            command: 'build'
            projects: |
              **/*MCT.Api.csproj
              **/*Test.csproj
            arguments: '--no-restore'

        - task: DotNetCoreCLI@2
          displayName: MCT.API - test
          inputs:
            command: 'test'
            projects: |
              **/*MCT.Api.Test.csproj
              **/*MCT.Api.Business.Test.csproj
            arguments: '--no-build --collect "Code coverage" --settings "$(Build.SourcesDirectory)$(runSettings)"'
            testRunTitle: 'Unit Test - Gated Build'

        - task: BuildQualityChecks@9
          inputs:
            checkWarnings: true
            warningFailOption: 'fixed'
            warningThreshold: '5'
            showStatistics: true
            checkCoverage: true
            coverageFailOption: 'fixed'
            coverageType: 'blocks'
            treat0of0as100: true
            coverageThreshold: '50'

        - task: DotNetCoreCLI@2
          displayName: MCT.Database - build
          inputs:
            command: 'build'
            projects: '**/*database.csproj'
            arguments: '--no-restore'