trigger: none
pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - dev
    - release 
    
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 'mct1espool'
      image: mct1esptwindows
      os: windows 
    stages:
    - stage: stage
      displayName: QG
      jobs:
      - job: job
        displayName: Job
        steps:
        - task: SonarQubePrepare@5
          displayName: Prepare Sonar Analysis
          inputs:
            SonarQube: 'mct-portal-sonar'
            scannerMode: 'MSBuild'
            projectKey: 'MCT_vNext_API'
            projectName: 'MCT_vNext_API_#Tools'
            projectVersion: '$(Build.BuildId)'
        - task: UseDotNet@2
          displayName: Use .Net 6.0.x
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
        - task: DotNetCoreCLI@2
          displayName: MCT.API - restore
          inputs:
            command: 'restore'
            projects: |
              **/*MCT.Api.csproj
              **/*Test.csproj
            feedsToUse: 'select'
            vstsFeed: 'c1eb1d13-5333-4112-95b2-2e514c22c241/e7a9b03a-3e9e-4ae7-b444-a06a80ff3074'
            includeNuGetOrg: false
        - task: DotNetCoreCLI@2
          displayName: MCT.API - build
          inputs:
            command: 'build'
            projects: |
              **/*MCT.Api.csproj
              **/*Test.csproj
            arguments: '--no-restore'

        - task: DotNetCoreCLI@2
          displayName: MCT.API - test
          inputs:
            command: 'test'
            projects: |
              **/*MCT.API.Test.csproj
            arguments: '--no-build --collect "Code coverage" --settings "$(Build.SourcesDirectory)/src/api/MCT.API.Test/codecoverage.runsettings"'
            testRunTitle: 'Unit Test - Gated Build'
          
        - task: DotNetCoreCLI@2
          displayName: MCT.API.Business - test
          inputs:
            command: 'test'
            projects: |
              **/*MCT.Business.Test.csproj
            arguments: '--no-build --collect "Code coverage" --settings "$(Build.SourcesDirectory)/src/api/MCT.Business.Test/codecoverage.runsettings"'
            testRunTitle: 'Unit Test Business - Gated Build'
          
        - task: SonarQubeAnalyze@5
          displayName: Analyse Build
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
        - task: SonarQubePublish@5
          displayName: Publish Sonar Report
          inputs:
            pollingTimeoutSec: '300'