trigger:
  branches:
    include:
    - dev 
    - release1/*
  paths:
    include:
     - src/adf/*

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: mct1espool
      image: mct1esimageubantu
      os: linux
    sdl:
      sourceAnalysisPool:
        name: mct1espool
        image: mct1esptwindows
        os: windows
  
    stages:
      - stage: 'Build'
        jobs:
          - job: Build_Adf_Arm_Template
            displayName: 'ADF Build ARM template'
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(Build.SourcesDirectory)/src/adf/ARMTemplate
                artifactName: ArmTemplate
                publishLocation: 'Container'  
            workspace:
              clean: all
            variables:
              devAdf: '/subscriptions/82e2a940-5e8b-42ab-b1ff-2af70bda7def/resourceGroups/mct-rg-dev/providers/Microsoft.DataFactory/factories/localdfmct1'
            steps:
              - task: NodeTool@0
                inputs:
                  versionSpec: '18.x'
                displayName: 'Install Node.js'
              - task: Npm@1
                inputs:
                  command: 'install'
                  workingDir: '$(Build.SourcesDirectory)/src/adf/' 
                  verbose: true
                displayName: 'Install npm package'

      # ADF  Validates all on adf-code.
              - task: Npm@1
                inputs:
                  command: 'custom'
                  workingDir: '$(Build.SourcesDirectory)/src/adf/'
                  customCommand: 'run build validate $(Build.SourcesDirectory)/src/adf/ $(devAdf)'
                displayName: 'Validate'
      # Validate and then generate the ARM template into the destination folder. Same as clicking "Publish" from UX
      # The ARM template generated is not published to the ‘Live’ version of the factory. Deployment should be done using a release pipeline.
              - task: Npm@1
                inputs: 
                  command: 'custom'
                  workingDir: '$(Build.SourcesDirectory)/src/adf/'
                  customCommand: 'run build export $(Build.SourcesDirectory)/src/adf/ $(devAdf) "ARMTemplate"'
                displayName: 'Validate and Generate ARM template'

    ## Deploy to Dev1
      - stage: 'Deploy_Dev1'
        dependsOn: 'Build'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
        jobs:
          - deployment: ADF_Deployment_On_Dev1
            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
              - input: pipelineArtifact
                artifactName: ArmTemplate 
                targetPath: $(System.DefaultWorkingDirectory)/ArmTemplate
            environment: 'DEV1'
            variables:
            - group: mct-adf-dev1
            strategy:
              runOnce:
                deploy:
                  steps:                   
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_Dataverse)|'$(dataVerseUri)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying Data verse URL  
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_managedCredentials)|'$(managedCredentials)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying User managed Identity  

                  # Stop ADF triggers
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-dev1'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Stop-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Stop ADF Triggers'
                    - task: AzureResourceManagerTemplateDeployment@3
                      inputs:
                        deploymentScope: 'Resource Group'
                        azureResourceManagerConnection: 'mct-dev1'
                        subscriptionId: '$(subscription-Id)'
                        action: 'Create Or Update Resource Group'
                        resourceGroupName: '$(resource-group)'
                        location: 'WestUS'
                        templateLocation: 'Linked artifact'
                        csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json'
                        csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateParametersForFactory.json'
                        overrideParameters: '-factoryName "$(data_factory_name)" -pac_sql_prd_connectionString "$(pac_sql_prd_connectionString)" -HRDataLake_ADLSGen2_properties_typeProperties_url "$(HRDataLake_ADLSGen2_properties_typeProperties_url)" -pac_syn_prd_connectionString "$(pac_syn_prd_connectionString)" -AzureBlobStorage_properties_typeProperties_serviceEndpoint "$(AzureBlobStorage_properties_typeProperties_serviceEndpoint)'
                        deploymentMode: 'Incremental'

                        # Start ADF triggers              
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-dev1'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Start-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Start ADF Triggers'
            

    ## Deploy to UAT1
      - stage: 'Deploy_Uat1'
        dependsOn: 'Build'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release1'))
        jobs:
          - deployment: ADF_Deployment_On_Uat1
            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
              - input: pipelineArtifact
                artifactName: ArmTemplate 
                targetPath: $(System.DefaultWorkingDirectory)/ArmTemplate
            environment: 'UAT1'
            variables:
            - group: mct-adf-uat1
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_Dataverse)|'$(dataVerseUri)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying Data verse URL  
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_managedCredentials)|'$(managedCredentials)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying User managed Identity  

                    # Stop ADF triggers
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-uat1'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Stop-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Stop ADF Triggers'
                    - task: AzureResourceManagerTemplateDeployment@3
                      inputs:
                        deploymentScope: 'Resource Group'
                        azureResourceManagerConnection: 'mct-uat1'
                        subscriptionId: '$(subscription-Id)'
                        action: 'Create Or Update Resource Group'
                        resourceGroupName: '$(resource-group)'
                        location: 'WestUS'
                        templateLocation: 'Linked artifact'
                        csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json'
                        csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateParametersForFactory.json'
                        overrideParameters: '-factoryName "$(data_factory_name)" -pac_sql_prd_connectionString "$(pac_sql_prd_connectionString)" -HRDataLake_ADLSGen2_properties_typeProperties_url "$(HRDataLake_ADLSGen2_properties_typeProperties_url)" -pac_syn_prd_connectionString "$(pac_syn_prd_connectionString)"'
                        deploymentMode: 'Incremental'
                        
                          # Start ADF triggers              
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-uat1'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Start-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Start ADF Triggers'

    ## Deploy to PROD
      - stage: 'Deploy_Prod'
        dependsOn: 'Deploy_Uat1'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release1'))
        jobs:
          - deployment: ADF_Deployment_On_Prod
            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
              - input: pipelineArtifact
                artifactName: ArmTemplate 
                targetPath: $(System.DefaultWorkingDirectory)/ArmTemplate
            environment: 'PROD'
            variables:
            - group: mct-adf-prod
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_Dataverse)|'$(dataVerseUri)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying Data verse URL  
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_managedCredentials)|'$(managedCredentials)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying User managed Identity  

                    # Stop ADF triggers
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-prod'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Stop-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Stop ADF Triggers'
                    - task: AzureResourceManagerTemplateDeployment@3
                      inputs:
                        deploymentScope: 'Resource Group'
                        azureResourceManagerConnection: 'mct-prod'
                        subscriptionId: '$(subscription-Id)'
                        action: 'Create Or Update Resource Group'
                        resourceGroupName: '$(resource-group)'
                        location: 'WestUS'
                        templateLocation: 'Linked artifact'
                        csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json'
                        csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateParametersForFactory.json'
                        overrideParameters: '-factoryName "$(data_factory_name)" -pac_sql_prd_connectionString "$(pac_sql_prd_connectionString)" -HRDataLake_ADLSGen2_properties_typeProperties_url "$(HRDataLake_ADLSGen2_properties_typeProperties_url)" -pac_syn_prd_connectionString "$(pac_syn_prd_connectionString)"'
                        deploymentMode: 'Incremental'
                        
                          # Start ADF triggers              
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-prod'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Start-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Start ADF Triggers'

      - stage: 'Deploy_Proddr'
        dependsOn: 'Deploy_Uat1'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release1'))
        jobs:
          - deployment: ADF_Deployment_On_Proddr
            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
              - input: pipelineArtifact
                artifactName: ArmTemplate 
                targetPath: $(System.DefaultWorkingDirectory)/ArmTemplate
            environment: 'PRODDR'
            variables:
            - group: mct-adf-proddr
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_Dataverse)|'$(dataVerseUri)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying Data verse URL  
                    - task: CmdLine@2
                      inputs:
                        script: "sed -i 's|$(old_managedCredentials)|'$(managedCredentials)'|' $(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json"
                      displayName: Modifying User managed Identity  

                    # Stop ADF triggers
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-proddr'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Stop-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Stop ADF Triggers'
                    - task: AzureResourceManagerTemplateDeployment@3
                      inputs:
                        deploymentScope: 'Resource Group'
                        azureResourceManagerConnection: 'mct-proddr'
                        subscriptionId: '$(subscription-Id)'
                        action: 'Create Or Update Resource Group'
                        resourceGroupName: '$(resource-group)'
                        location: 'EastUS'
                        templateLocation: 'Linked artifact'
                        csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateForFactory.json'
                        csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplate/ARMTemplateParametersForFactory.json'
                        overrideParameters: '-factoryName "$(data_factory_name)" -pac_sql_prddr_connectionString "$(pac_sql_prddr_connectionString)" -HRDataLake_ADLSGen2_properties_typeProperties_url "$(HRDataLake_ADLSGen2_properties_typeProperties_url)" -pac_syn_prddr_connectionString "$(pac_syn_prddr_connectionString)"'
                        deploymentMode: 'Incremental'
                        
                          # Start ADF triggers              
                    - task: AzurePowerShell@5
                      inputs:
                        azureSubscription: 'mct-proddr'
                        TargetAzurePs: LatestVersion
                        ScriptType: 'InlineScript'
                        Inline: |
                          $adfName = "$(data_factory_name)"
                          $resourceGroupName = "$(resource-group)"
                          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName
                          foreach ($trigger in $triggers) {
                          Start-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $adfName -Name $trigger.Name -Force
                          }
                      displayName: 'Start ADF Triggers'  